package com.hinnka.mycamera.raw

// Extracted without fitting from PhotonCamera_20261006_185625.dng.
// Source SHA-256: b679ed4227ec627f0b9f05b5db36864b62fca0b019971bf059eeeec0267d0b04
// Generated by tools/extract_fallback_calibration.py.
internal object FixedRawCalibration {
    const val ILLUMINANT1 = 21
    fun colorMatrix1(): FloatArray = floatArrayOf(
        0.82950000f, -0.30550000f, -0.06240000f,
        -0.42770000f, 1.28200000f, 0.15810000f,
        -0.16980000f, 0.32650000f, 0.51680000f,
    )
    fun cameraCalibration1(): FloatArray = floatArrayOf(
        0.99218800f, 0.00000000f, 0.00000000f,
        0.00000000f, 1.00000000f, 0.00000000f,
        0.00000000f, 0.00000000f, 1.01562500f,
    )
    const val ILLUMINANT2 = 17
    fun colorMatrix2(): FloatArray = floatArrayOf(
        0.90540000f, -0.41370000f, 0.03050000f,
        -0.35840000f, 1.17330000f, 0.20870000f,
        -0.08470000f, 0.22130000f, 0.58070000f,
    )
    fun cameraCalibration2(): FloatArray = floatArrayOf(
        0.99218800f, 0.00000000f, 0.00000000f,
        0.00000000f, 1.00000000f, 0.00000000f,
        0.00000000f, 0.00000000f, 1.00781300f,
    )
}
