package com.hinnka.mycamera.raw

// Generated by tools/extract_mgc_standard_gamma.py; do not edit.
// MGC V25 libgcastartup.so SHA-256: 76966e7c150dfcb2795ea5b2119827a7e90b13d8c03035dbc4de583d9d12eaa6
// Google Stock defaults: 33 doubles at VA/file 0xF3F138; exponent at 0x6B8E88.
internal object MgcStandardGammaData {
    const val EXPONENT = 0.45454543828964233
    val KNOTS = doubleArrayOf(
        0.0, 0.003959, 0.018405, 0.043836,
        0.073478, 0.104864, 0.13715, 0.170288,
        0.204674, 0.240396, 0.277553, 0.31608,
        0.355398, 0.394413, 0.432555, 0.469181,
        0.505111, 0.540626, 0.575595, 0.61008,
        0.644066, 0.677381, 0.710066, 0.742155,
        0.773639, 0.804525, 0.834824, 0.864424,
        0.893152, 0.920521, 0.947214, 0.973732,
        1.0,
    )
}
