// Generated by tools/generate_srgb_color_matrix_policy.py; do not edit coefficients.
package com.hinnka.mycamera.raw

import kotlin.math.sqrt

internal object SrgbColorMatrixPolicy {
    // Positive row normalization removes channel gains and DNG's global normalization.
    // All three row directions must match one reference, within 1/128 in unit-vector
    // distance. This allows coarse vendor quantization and DNG writer rounding,
    // without accepting arbitrary invertible matrices. Unknown illuminants do not match.
    fun isPlaceholder(matrix: FloatArray, illuminant: Int): Boolean {
        val references = when (illuminant) {
            17 -> ILLUMINANT_17
            20 -> ILLUMINANT_20
            21 -> ILLUMINANT_21
            22 -> ILLUMINANT_22
            23 -> ILLUMINANT_23
            else -> return false
        }
        if (matrix.size != 9 || matrix.any { !it.isFinite() }) return false
        val normalized = DoubleArray(9)
        for (row in 0..2) {
            val offset = row * 3
            val norm = sqrt((0..2).sumOf { matrix[offset + it].toDouble() * matrix[offset + it] })
            if (norm <= 0.0) return false
            for (col in 0..2) normalized[offset + col] = matrix[offset + col] / norm
        }
        return references.any { reference ->
            (0..2).all { row ->
                (0..2).sumOf { col ->
                    val difference = normalized[row * 3 + col] - reference[row * 3 + col]
                    difference * difference
                } <= 1.0 / (128.0 * 128.0)
            }
        }
    }

    private val ILLUMINANT_17 = arrayOf(
        doubleArrayOf(0.813830780315, -0.563242197715, -0.142960441116, -0.441177918240, 0.897414059585, -0.003170191814, 0.046917252215, -0.110280374442, 0.992792531427),
        doubleArrayOf(0.815400797265, -0.563102991294, -0.134300264388, -0.434722701214, 0.900470956368, -0.012970342611, 0.042551963233, -0.105421912723, 0.993516759166),
    )

    private val ILLUMINANT_20 = arrayOf(
        doubleArrayOf(0.886382734787, -0.442004635220, -0.137686418776, -0.456487582201, 0.889561832221, 0.017286814365, 0.050938204182, -0.171036834278, 0.983947000948),
        doubleArrayOf(0.887323242367, -0.441075082597, -0.134574273423, -0.447624698223, 0.894141744616, 0.011944457955, 0.038927978823, -0.160326527413, 0.986296110239),
    )

    private val ILLUMINANT_21 = arrayOf(
        doubleArrayOf(0.894898004135, -0.424502899397, -0.137676616021, -0.458928857961, 0.888255120603, 0.019675976529, 0.051609203774, -0.189233747171, 0.980574871704),
        doubleArrayOf(0.895762516456, -0.423503157407, -0.135109547330, -0.449678750877, 0.893067723448, 0.014800754870, 0.037211885156, -0.176846957406, 0.983534660934),
    )

    private val ILLUMINANT_22 = arrayOf(
        doubleArrayOf(0.900393375690, -0.412687505585, -0.137770794243, -0.460620342808, 0.887343897003, 0.021206325528, 0.052032571221, -0.204181460492, 0.977549253349),
        doubleArrayOf(0.901208762561, -0.411645847776, -0.135537678498, -0.451102222465, 0.892317528320, 0.016619673274, 0.035650619558, -0.190441882142, 0.981050927756),
    )

    private val ILLUMINANT_23 = arrayOf(
        doubleArrayOf(0.880170582073, -0.454216295058, -0.137794425708, -0.454826396105, 0.890444524282, 0.015540224637, 0.050469011336, -0.160602705036, 0.985727979734),
        doubleArrayOf(0.881166182110, -0.453341470202, -0.134267162408, -0.446227079090, 0.894865603080, 0.009846131799, 0.039812024246, -0.150868176816, 0.987751889874),
    )
}
