# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy>=2.2"]
# ///
"""Generate identical Kotlin/native sRGB ColorMatrix placeholder detection.

Run with uv run tools/generate_srgb_color_matrix_policy.py. ColorMatrix is
XYZ(illuminant) -> camera, so compare against inverse(sRGB -> XYZ D50)
after Bradford adaptation, allowing positive per-channel gains. This is a
bounded similarity heuristic, not proof that an arbitrary calibration is wrong.
"""
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
B = np.array([[.8951, .2664, -.1614], [-.7502, 1.7135, .0367], [.0389, -.0685, 1.0296]])


def xyz(x, y):
    return np.array([x / y, 1., (1 - x - y) / y])


D50 = xyz(.3457, .3585)
D65 = xyz(.3127, .3290)


def adapt(white):
    return np.linalg.solve(B, np.diag((B @ D50) / (B @ white)) @ B)


primaries = np.column_stack([xyz(.64, .33), xyz(.30, .60), xyz(.15, .06)])
srgb = adapt(D65) @ primaries @ np.diag(np.linalg.solve(primaries, D65))
# Same quantized signature as ForwardMatrixPolicy / native-lib.cpp.
quantized = np.array([[56, 49, 18], [28, 92, 8], [2, 12, 91]]) / 128.
quantized *= (D50 / quantized.sum(axis=1))[:, None]
whites = {17: np.array([1.09850, 1., .35585]), 20: xyz(.33242, .34743),
          21: D65, 22: xyz(.29902, .31485), 23: D50}
bases = {}
for illuminant, white in whites.items():
    bases[illuminant] = []
    for forward in (srgb, quantized):
        basis = np.linalg.solve(forward, adapt(white))
        bases[illuminant].append(basis / np.linalg.norm(basis, axis=1)[:, None])

notice = '// Generated by tools/generate_srgb_color_matrix_policy.py; do not edit coefficients.\n'
comment = '''    // Positive row normalization removes channel gains and DNG's global normalization.
    // All three row directions must match one reference, within 1/128 in unit-vector
    // distance. This allows coarse vendor quantization and DNG writer rounding,
    // without accepting arbitrary invertible matrices. Unknown illuminants do not match.
'''
kotlin = notice + '''package com.hinnka.mycamera.raw

import kotlin.math.sqrt

internal object SrgbColorMatrixPolicy {
''' + comment + '''    fun isPlaceholder(matrix: FloatArray, illuminant: Int): Boolean {
        val references = when (illuminant) {
'''
for illuminant in bases:
    kotlin += f'            {illuminant} -> ILLUMINANT_{illuminant}\n'
kotlin += '''            else -> return false
        }
        if (matrix.size != 9 || matrix.any { !it.isFinite() }) return false
        val normalized = DoubleArray(9)
        for (row in 0..2) {
            val offset = row * 3
            val norm = sqrt((0..2).sumOf { matrix[offset + it].toDouble() * matrix[offset + it] })
            if (norm <= 0.0) return false
            for (col in 0..2) normalized[offset + col] = matrix[offset + col] / norm
        }
        return references.any { reference ->
            (0..2).all { row ->
                (0..2).sumOf { col ->
                    val difference = normalized[row * 3 + col] - reference[row * 3 + col]
                    difference * difference
                } <= 1.0 / (128.0 * 128.0)
            }
        }
    }
'''
header = notice + '''#pragma once
#include <cmath>

namespace srgb_color_matrix_policy {
''' + comment
for illuminant, references in bases.items():
    kotlin += f'\n    private val ILLUMINANT_{illuminant} = arrayOf(\n'
    header += f'inline constexpr double illuminant{illuminant}[2][9] = {{\n'
    for reference in references:
        values = ', '.join(f'{value:.12f}' for value in reference.ravel())
        kotlin += f'        doubleArrayOf({values}),\n'
        header += f'    {{{values}}},\n'
    kotlin += '    )\n'
    header += '};\n'
kotlin += '}\n'
header += '''
// Input must first pass isUsableSourceMatrix (including bitwise finite checks).
inline bool isPlaceholder(const float *matrix, int illuminant) {
    const double (*references)[9] = nullptr;
    switch (illuminant) {
'''
for illuminant in bases:
    header += f'    case {illuminant}: references = illuminant{illuminant}; break;\n'
header += '''    default: return false;
    }
    double normalized[9];
    for (int row = 0; row < 3; ++row) {
        const int offset = row * 3;
        double normSquared = 0.0;
        for (int col = 0; col < 3; ++col) {
            const double value = matrix[offset + col];
            normSquared += value * value;
        }
        if (normSquared <= 0.0) return false;
        const double norm = std::sqrt(normSquared);
        for (int col = 0; col < 3; ++col) normalized[offset + col] = matrix[offset + col] / norm;
    }
    for (int reference = 0; reference < 2; ++reference) {
        bool matches = true;
        for (int row = 0; row < 3; ++row) {
            double error = 0.0;
            for (int col = 0; col < 3; ++col) {
                const int index = row * 3 + col;
                const double difference = normalized[index] - references[reference][index];
                error += difference * difference;
            }
            if (error > 1.0 / (128.0 * 128.0)) matches = false;
        }
        if (matches) return true;
    }
    return false;
}
}
'''
(ROOT / 'app/src/main/java/com/hinnka/mycamera/raw/SrgbColorMatrixPolicy.kt').write_text(kotlin, encoding='utf-8')
(ROOT / 'app/src/main/cpp/srgb_color_matrix_policy.h').write_text(header, encoding='utf-8')
